// NoFap page: persisted state shape, streak math, and the hardcoded
// motivation content (quotes, milestones, panic lines). Content is
// intentionally harsh — that's the brief. Mixed English/Turkish.

export interface NofapRelapse {
  at: number;       // epoch ms of the relapse
  streakMs: number; // length of the streak that was lost
}

export interface NofapPanic {
  at: number;
  survived: boolean;
}

export interface NofapState {
  v: 1;
  startedAt: number | null; // epoch ms of current streak start; null = never started
  bestMs: number;           // longest streak ever (ms)
  relapses: NofapRelapse[]; // newest first
  panics: NofapPanic[];     // newest first
}

export const NOFAP_DEFAULT: NofapState = {
  v: 1,
  startedAt: null,
  bestMs: 0,
  relapses: [],
  panics: [],
};

// Synced blobs can arrive partial or stale from another device/old version —
// coerce anything malformed back to a usable state instead of crashing.
export function sanitizeState(raw: unknown): NofapState {
  const r = (raw && typeof raw === "object" ? raw : {}) as Partial<NofapState>;
  const startedAt =
    typeof r.startedAt === "number" && r.startedAt > 0
      ? Math.min(r.startedAt, Date.now())
      : null;
  return {
    v: 1,
    startedAt,
    bestMs: typeof r.bestMs === "number" && r.bestMs > 0 ? r.bestMs : 0,
    relapses: Array.isArray(r.relapses)
      ? r.relapses.filter((x) => x && typeof x.at === "number").slice(0, 200)
      : [],
    panics: Array.isArray(r.panics)
      ? r.panics.filter((x) => x && typeof x.at === "number").slice(0, 200)
      : [],
  };
}

export function splitDuration(ms: number) {
  const s = Math.max(0, Math.floor(ms / 1000));
  return {
    days: Math.floor(s / 86400),
    hours: Math.floor((s % 86400) / 3600),
    mins: Math.floor((s % 3600) / 60),
    secs: s % 60,
  };
}

export function formatDurationShort(ms: number): string {
  const { days, hours, mins } = splitDuration(ms);
  if (days > 0) return `${days}d ${hours}h`;
  if (hours > 0) return `${hours}h ${mins}m`;
  return `${mins}m`;
}

// Quotations by real, identifiable people, on self-mastery, habit, work,
// courage, time and starting again. Attributions are the widely-documented
// ones and were chosen conservatively: where a famous line is a traditional
// saying rather than one person's words it is credited as a proverb, and
// where the popular attribution is known to be wrong the line is either
// credited to its real source or left out entirely. Mostly English with a
// solid Turkish set (lang: "tr").
export const QUOTES: { text: string; author: string; lang: "en" | "tr" }[] = [
  // --- Stoics ---
  { text: "You have power over your mind — not outside events. Realize this, and you will find strength.", author: "Marcus Aurelius", lang: "en" },
  { text: "The happiness of your life depends upon the quality of your thoughts.", author: "Marcus Aurelius", lang: "en" },
  { text: "Waste no more time arguing about what a good man should be. Be one.", author: "Marcus Aurelius", lang: "en" },
  { text: "If it is not right, do not do it; if it is not true, do not say it.", author: "Marcus Aurelius", lang: "en" },
  { text: "The impediment to action advances action. What stands in the way becomes the way.", author: "Marcus Aurelius", lang: "en" },
  { text: "Perform every act of your life as though it were the last act of your life.", author: "Marcus Aurelius", lang: "en" },
  { text: "The best revenge is to be unlike him who performed the injury.", author: "Marcus Aurelius", lang: "en" },
  { text: "Confine yourself to the present.", author: "Marcus Aurelius", lang: "en" },
  { text: "Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present.", author: "Marcus Aurelius", lang: "en" },
  { text: "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", author: "Marcus Aurelius", lang: "en" },
  { text: "Look well into thyself; there is a source of strength which will always spring up if thou wilt always look there.", author: "Marcus Aurelius", lang: "en" },
  { text: "You could leave life right now. Let that determine what you do and say and think.", author: "Marcus Aurelius", lang: "en" },
  { text: "How much time he gains who does not look to see what his neighbour says or does or thinks.", author: "Marcus Aurelius", lang: "en" },
  { text: "It is not death that a man should fear, but he should fear never beginning to live.", author: "Marcus Aurelius", lang: "en" },
  { text: "A man's worth is no greater than the worth of his ambitions.", author: "Marcus Aurelius", lang: "en" },
  { text: "Be tolerant with others and strict with yourself.", author: "Marcus Aurelius", lang: "en" },
  { text: "Nowhere can a man find a quieter or more untroubled retreat than in his own soul.", author: "Marcus Aurelius", lang: "en" },
  { text: "Think of yourself as dead. You have lived your life. Now take what is left and live it properly.", author: "Marcus Aurelius", lang: "en" },
  { text: "The soul becomes dyed with the colour of its thoughts.", author: "Marcus Aurelius", lang: "en" },
  { text: "Reject your sense of injury and the injury itself disappears.", author: "Marcus Aurelius", lang: "en" },
  { text: "Loss is nothing else but change, and change is Nature's delight.", author: "Marcus Aurelius", lang: "en" },
  { text: "Whatever anyone does or says, I must be good.", author: "Marcus Aurelius", lang: "en" },
  { text: "Dwell on the beauty of life. Watch the stars, and see yourself running with them.", author: "Marcus Aurelius", lang: "en" },
  { text: "We suffer more often in imagination than in reality.", author: "Seneca", lang: "en" },
  { text: "It is not that we have a short time to live, but that we waste a lot of it.", author: "Seneca", lang: "en" },
  { text: "No man is free who is a slave to the flesh.", author: "Seneca", lang: "en" },
  { text: "Most powerful is he who has himself in his own power.", author: "Seneca", lang: "en" },
  { text: "Difficulties strengthen the mind, as labour does the body.", author: "Seneca", lang: "en" },
  { text: "As long as you live, keep learning how to live.", author: "Seneca", lang: "en" },
  { text: "He who is brave is free.", author: "Seneca", lang: "en" },
  { text: "It is not the man who has too little, but the man who craves more, that is poor.", author: "Seneca", lang: "en" },
  { text: "Begin at once to live, and count each separate day as a separate life.", author: "Seneca", lang: "en" },
  { text: "The greatest obstacle to living is expectancy, which hangs upon tomorrow and loses today.", author: "Seneca", lang: "en" },
  { text: "While we are postponing, life speeds by.", author: "Seneca", lang: "en" },
  { text: "It is a rough road that leads to the heights of greatness.", author: "Seneca", lang: "en" },
  { text: "The bravest sight in the world is to see a great man struggling against adversity.", author: "Seneca", lang: "en" },
  { text: "Sometimes even to live is an act of courage.", author: "Seneca", lang: "en" },
  { text: "If you really want to escape the things that harass you, what you need is not to be in a different place but to be a different person.", author: "Seneca", lang: "en" },
  { text: "Associate with those who will make a better man of you.", author: "Seneca", lang: "en" },
  { text: "Nothing is burdensome if taken lightly.", author: "Seneca", lang: "en" },
  { text: "Time discovers truth.", author: "Seneca", lang: "en" },
  { text: "It is not what happens to you, but how you react to it that matters.", author: "Epictetus", lang: "en" },
  { text: "No man is free who is not master of himself.", author: "Epictetus", lang: "en" },
  { text: "First say to yourself what you would be; and then do what you have to do.", author: "Epictetus", lang: "en" },
  { text: "Men are disturbed not by things, but by the views which they take of things.", author: "Epictetus", lang: "en" },
  { text: "Freedom is not procured by a full enjoyment of what is desired, but by controlling the desire.", author: "Epictetus", lang: "en" },
  { text: "If you want to improve, be content to be thought foolish and stupid.", author: "Epictetus", lang: "en" },
  { text: "Wealth consists not in having great possessions, but in having few wants.", author: "Epictetus", lang: "en" },
  { text: "Circumstances do not make the man, they only reveal him to himself.", author: "Epictetus", lang: "en" },
  { text: "He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has.", author: "Epictetus", lang: "en" },
  { text: "Don't explain your philosophy. Embody it.", author: "Epictetus", lang: "en" },
  { text: "Any person capable of angering you becomes your master.", author: "Epictetus", lang: "en" },
  { text: "No great thing is created suddenly.", author: "Epictetus", lang: "en" },
  { text: "Make the best use of what is in your power, and take the rest as it happens.", author: "Epictetus", lang: "en" },
  { text: "It is impossible for a man to learn what he thinks he already knows.", author: "Epictetus", lang: "en" },
  { text: "First learn the meaning of what you say, and then speak.", author: "Epictetus", lang: "en" },

  // --- Greece & Rome ---
  { text: "The first and greatest victory is to conquer yourself.", author: "Plato", lang: "en" },
  { text: "The beginning is the most important part of the work.", author: "Plato", lang: "en" },
  { text: "Knowledge which is acquired under compulsion obtains no hold on the mind.", author: "Plato", lang: "en" },
  { text: "Human behaviour flows from three main sources: desire, emotion and knowledge.", author: "Plato", lang: "en" },
  { text: "The unexamined life is not worth living.", author: "Socrates", lang: "en" },
  { text: "He is richest who is content with the least.", author: "Socrates", lang: "en" },
  { text: "Let him that would move the world first move himself.", author: "Socrates", lang: "en" },
  { text: "Know thyself.", author: "Inscription at the Temple of Delphi", lang: "en" },
  { text: "Nothing in excess.", author: "Inscription at the Temple of Delphi", lang: "en" },
  { text: "Moral excellence comes about as a result of habit.", author: "Aristotle", lang: "en" },
  { text: "We become just by doing just acts, temperate by doing temperate acts, brave by doing brave acts.", author: "Aristotle", lang: "en" },
  { text: "Happiness depends upon ourselves.", author: "Aristotle", lang: "en" },
  { text: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle", lang: "en" },
  { text: "The educated differ from the uneducated as much as the living from the dead.", author: "Aristotle", lang: "en" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act but a habit.", author: "Will Durant, summarising Aristotle", lang: "en" },
  { text: "Character is destiny.", author: "Heraclitus", lang: "en" },
  { text: "No man ever steps in the same river twice, for it is not the same river and he is not the same man.", author: "Heraclitus", lang: "en" },
  { text: "Big results require big ambitions.", author: "Heraclitus", lang: "en" },
  { text: "He who has begun is half done. Dare to be wise; begin!", author: "Horace", lang: "en" },
  { text: "Seize the day, trusting as little as possible in the future.", author: "Horace", lang: "en" },
  { text: "Adversity reveals genius, prosperity conceals it.", author: "Horace", lang: "en" },
  { text: "Dripping water hollows out stone, not through force but through persistence.", author: "Ovid", lang: "en" },
  { text: "Take rest; a field that has rested gives a bountiful crop.", author: "Ovid", lang: "en" },
  { text: "Fortune favours the bold.", author: "Virgil", lang: "en" },
  { text: "They can because they think they can.", author: "Virgil", lang: "en" },
  { text: "Anyone can hold the helm when the sea is calm.", author: "Publilius Syrus", lang: "en" },
  { text: "It is a bad plan that admits of no modification.", author: "Publilius Syrus", lang: "en" },
  { text: "While there's life, there's hope.", author: "Cicero", lang: "en" },
  { text: "The beginnings of all things are small.", author: "Cicero", lang: "en" },
  { text: "Any man can make mistakes, but only an idiot persists in his error.", author: "Cicero", lang: "en" },
  { text: "If you wish to make Pythocles rich, do not add to his money, but subtract from his desires.", author: "Epicurus", lang: "en" },
  { text: "Not what we have but what we enjoy constitutes our abundance.", author: "Epicurus", lang: "en" },
  { text: "The secret to happiness is freedom, and the secret to freedom is courage.", author: "Thucydides", lang: "en" },
  { text: "Walking is man's best medicine.", author: "Hippocrates", lang: "en" },
  { text: "Slow and steady wins the race.", author: "Aesop", lang: "en" },
  { text: "It is easy to be brave from a safe distance.", author: "Aesop", lang: "en" },
  { text: "No act of kindness, no matter how small, is ever wasted.", author: "Aesop", lang: "en" },
  { text: "Through hardship to the stars.", author: "Latin proverb", lang: "en" },
  { text: "While I breathe, I hope.", author: "Latin proverb", lang: "en" },
  { text: "I am not led, I lead.", author: "Latin motto", lang: "en" },

  // --- Eastern classics ---
  { text: "A journey of a thousand miles begins with a single step.", author: "Lao Tzu", lang: "en" },
  { text: "He who conquers others is strong; he who conquers himself is mighty.", author: "Lao Tzu", lang: "en" },
  { text: "He who knows others is wise; he who knows himself is enlightened.", author: "Lao Tzu", lang: "en" },
  { text: "He who is contented is rich.", author: "Lao Tzu", lang: "en" },
  { text: "Do the difficult things while they are easy, and do the great things while they are small.", author: "Lao Tzu", lang: "en" },
  { text: "Nature does not hurry, yet everything is accomplished.", author: "Lao Tzu", lang: "en" },
  { text: "When I let go of what I am, I become what I might be.", author: "Lao Tzu", lang: "en" },
  { text: "To the mind that is still, the whole universe surrenders.", author: "Lao Tzu", lang: "en" },
  { text: "A tree as big as a man's embrace springs from a tiny sprout.", author: "Lao Tzu", lang: "en" },
  { text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius", lang: "en" },
  { text: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius", lang: "en" },
  { text: "When anger rises, think of the consequences.", author: "Confucius", lang: "en" },
  { text: "The superior man is modest in his speech but exceeds in his actions.", author: "Confucius", lang: "en" },
  { text: "He who conquers himself is the mightiest warrior.", author: "Confucius", lang: "en" },
  { text: "Study the past if you would define the future.", author: "Confucius", lang: "en" },
  { text: "Real knowledge is to know the extent of one's ignorance.", author: "Confucius", lang: "en" },
  { text: "Wherever you go, go with all your heart.", author: "Confucius", lang: "en" },
  { text: "To see what is right and not do it is want of courage.", author: "Confucius", lang: "en" },
  { text: "Life is really simple, but we insist on making it complicated.", author: "Confucius", lang: "en" },
  { text: "Better a diamond with a flaw than a pebble without.", author: "Confucius", lang: "en" },
  { text: "When you know a thing, to hold that you know it; and when you do not know a thing, to allow that you do not know it — this is knowledge.", author: "Confucius", lang: "en" },
  { text: "The will to win, the desire to succeed, the urge to reach your full potential — these are the keys that will unlock the door to personal excellence.", author: "Eddie Robinson", lang: "en" },
  { text: "In the midst of chaos, there is also opportunity.", author: "Sun Tzu", lang: "en" },
  { text: "Victorious warriors win first and then go to war, while defeated warriors go to war first and then seek to win.", author: "Sun Tzu", lang: "en" },
  { text: "The supreme art of war is to subdue the enemy without fighting.", author: "Sun Tzu", lang: "en" },
  { text: "If you know the enemy and know yourself, you need not fear the result of a hundred battles.", author: "Sun Tzu", lang: "en" },
  { text: "Opportunities multiply as they are seized.", author: "Sun Tzu", lang: "en" },
  { text: "He will win who knows when to fight and when not to fight.", author: "Sun Tzu", lang: "en" },
  { text: "Let your plans be dark and impenetrable as night, and when you move, fall like a thunderbolt.", author: "Sun Tzu", lang: "en" },
  { text: "It is better to conquer yourself than to win a thousand battles.", author: "The Dhammapada", lang: "en" },
  { text: "All that we are is the result of what we have thought.", author: "The Dhammapada", lang: "en" },
  { text: "Drop by drop is the water pot filled.", author: "The Dhammapada", lang: "en" },
  { text: "You yourself must strive. The Buddhas only point the way.", author: "The Dhammapada", lang: "en" },
  { text: "There is no fire like passion, no grip like hatred, no net like delusion.", author: "The Dhammapada", lang: "en" },
  { text: "Health is the greatest gift, contentment the greatest wealth.", author: "The Dhammapada", lang: "en" },
  { text: "Irrigators channel waters; fletchers straighten arrows; carpenters bend wood; the wise master themselves.", author: "The Dhammapada", lang: "en" },
  { text: "You have the right to work, but never to the fruit of the work.", author: "Bhagavad Gita", lang: "en" },
  { text: "A man is made by his belief. As he believes, so he is.", author: "Bhagavad Gita", lang: "en" },
  { text: "Do not seek pleasure for its own sake.", author: "Miyamoto Musashi", lang: "en" },
  { text: "Do not regret what you have done.", author: "Miyamoto Musashi", lang: "en" },
  { text: "Accept everything just the way it is.", author: "Miyamoto Musashi", lang: "en" },
  { text: "Do nothing which is of no use.", author: "Miyamoto Musashi", lang: "en" },
  { text: "Think lightly of yourself and deeply of the world.", author: "Miyamoto Musashi", lang: "en" },
  { text: "Today is victory over yourself of yesterday.", author: "Miyamoto Musashi", lang: "en" },
  { text: "Do not be negligent, even in trifling matters.", author: "Miyamoto Musashi", lang: "en" },
  { text: "You must understand that there is more than one path to the top of the mountain.", author: "Miyamoto Musashi", lang: "en" },
  { text: "Perceive that which cannot be seen with the eye.", author: "Miyamoto Musashi", lang: "en" },
  { text: "Do not pray for an easy life; pray for the strength to endure a difficult one.", author: "Bruce Lee", lang: "en" },
  { text: "I fear not the man who has practised ten thousand kicks once, but I fear the man who has practised one kick ten thousand times.", author: "Bruce Lee", lang: "en" },
  { text: "If you spend too much time thinking about a thing, you will never get it done.", author: "Bruce Lee", lang: "en" },
  { text: "Mistakes are always forgivable, if one has the courage to admit them.", author: "Bruce Lee", lang: "en" },
  { text: "Empty your mind, be formless, shapeless — like water.", author: "Bruce Lee", lang: "en" },
  { text: "Knowing is not enough; we must apply. Willing is not enough; we must do.", author: "Johann Wolfgang von Goethe", lang: "en" },
  { text: "Before enlightenment, chop wood, carry water. After enlightenment, chop wood, carry water.", author: "Zen saying", lang: "en" },
  { text: "The obstacle is the path.", author: "Zen proverb", lang: "en" },
  { text: "When you reach the top of the mountain, keep climbing.", author: "Zen proverb", lang: "en" },
  { text: "Fall seven times, stand up eight.", author: "Japanese proverb", lang: "en" },
  { text: "Vision without action is a daydream. Action without vision is a nightmare.", author: "Japanese proverb", lang: "en" },
  { text: "The bamboo that bends is stronger than the oak that resists.", author: "Japanese proverb", lang: "en" },
  { text: "The best time to plant a tree was twenty years ago. The second best time is now.", author: "Chinese proverb", lang: "en" },
  { text: "Be not afraid of going slowly; be afraid only of standing still.", author: "Chinese proverb", lang: "en" },
  { text: "A journey of a thousand miles is walked one step at a time.", author: "Chinese proverb", lang: "en" },
  { text: "Little by little, one travels far.", author: "Spanish proverb", lang: "en" },
  { text: "If you want to go fast, go alone. If you want to go far, go together.", author: "African proverb", lang: "en" },
  { text: "Smooth seas do not make skilful sailors.", author: "African proverb", lang: "en" },
  { text: "Ask the experienced rather than the learned.", author: "Arabic proverb", lang: "en" },
  { text: "The wind does not break a tree that bends.", author: "African proverb", lang: "en" },
  { text: "This too shall pass.", author: "Persian adage", lang: "en" },
  { text: "You will never plough a field by turning it over in your mind.", author: "Irish proverb", lang: "en" },
  { text: "Begin to weave and God will give you the thread.", author: "German proverb", lang: "en" },
  { text: "A rolling stone gathers no moss.", author: "English proverb", lang: "en" },

  // --- Islamic and Middle Eastern tradition ---
  { text: "The strong man is not the one who can wrestle others down; the strong man is the one who controls himself when he is angry.", author: "Prophet Muhammad (Sahih al-Bukhari)", lang: "en" },
  { text: "The most beloved deeds to God are those done regularly, even if they are small.", author: "Prophet Muhammad (Sahih al-Bukhari)", lang: "en" },
  { text: "Take advantage of five before five: your youth before old age, your health before sickness, your wealth before poverty, your free time before busyness, and your life before your death.", author: "Prophet Muhammad (Hadith)", lang: "en" },
  { text: "Tie your camel first, then put your trust in God.", author: "Prophet Muhammad (Sunan al-Tirmidhi)", lang: "en" },
  { text: "Do not let your difficulties fill you with anxiety; after all it is only in the darkest nights that stars shine more brightly.", author: "Ali ibn Abi Talib", lang: "en" },
  { text: "Your remedy is within you, but you do not sense it. Your sickness is from you, but you do not perceive it.", author: "Ali ibn Abi Talib", lang: "en" },
  { text: "Patience is of two kinds: patience over what pains you, and patience against what you covet.", author: "Ali ibn Abi Talib", lang: "en" },
  { text: "The tongue is a beast; if it is let loose, it devours.", author: "Ali ibn Abi Talib", lang: "en" },
  { text: "He who has a thousand friends has not a friend to spare, and he who has one enemy will meet him everywhere.", author: "Ali ibn Abi Talib", lang: "en" },
  { text: "Knowledge without action is madness, and action without knowledge is vanity.", author: "Al-Ghazali", lang: "en" },
  { text: "The one who does not know, and does not know that he does not know, is a fool — shun him.", author: "Arabic saying", lang: "en" },
  { text: "The past is more like the future than one drop of water is like another.", author: "Ibn Khaldun", lang: "en" },
  { text: "Have patience. All things are difficult before they become easy.", author: "Saadi Shirazi", lang: "en" },
  { text: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.", author: "Rumi", lang: "en" },
  { text: "The wound is the place where the Light enters you.", author: "Rumi", lang: "en" },
  { text: "Set your life on fire. Seek those who fan your flames.", author: "Rumi", lang: "en" },
  { text: "Do not be satisfied with the stories that come before you. Unfold your own myth.", author: "Rumi", lang: "en" },
  { text: "What you seek is seeking you.", author: "Rumi", lang: "en" },
  { text: "Sell your cleverness and buy bewilderment.", author: "Rumi", lang: "en" },
  { text: "Raise your words, not your voice. It is rain that grows flowers, not thunder.", author: "Rumi", lang: "en" },

  // --- European philosophers ---
  { text: "He who moves not forward, goes backward.", author: "Johann Wolfgang von Goethe", lang: "en" },
  { text: "Everything is hard before it is easy.", author: "Johann Wolfgang von Goethe", lang: "en" },
  { text: "Treat people as if they were what they ought to be, and you help them to become what they are capable of being.", author: "Johann Wolfgang von Goethe", lang: "en" },
  { text: "A man sees in the world what he carries in his heart.", author: "Johann Wolfgang von Goethe", lang: "en" },
  { text: "It is not doing the thing we like to do, but liking the thing we have to do, that makes life blessed.", author: "Johann Wolfgang von Goethe", lang: "en" },
  { text: "Nothing is worth more than this day.", author: "Johann Wolfgang von Goethe", lang: "en" },
  { text: "The person born with a talent they are meant to use will find their greatest happiness in using it.", author: "Johann Wolfgang von Goethe", lang: "en" },
  { text: "He who has a why to live can bear almost any how.", author: "Friedrich Nietzsche", lang: "en" },
  { text: "That which does not kill us makes us stronger.", author: "Friedrich Nietzsche", lang: "en" },
  { text: "He who cannot obey himself will be commanded.", author: "Friedrich Nietzsche", lang: "en" },
  { text: "No one can construct for you the bridge upon which precisely you must cross the stream of life.", author: "Friedrich Nietzsche", lang: "en" },
  { text: "You must have chaos within you to give birth to a dancing star.", author: "Friedrich Nietzsche", lang: "en" },
  { text: "The snake which cannot cast its skin has to die.", author: "Friedrich Nietzsche", lang: "en" },
  { text: "Whoever fights monsters should see to it that in the process he does not become a monster.", author: "Friedrich Nietzsche", lang: "en" },
  { text: "One repays a teacher badly if one remains only a pupil.", author: "Friedrich Nietzsche", lang: "en" },
  { text: "The higher we soar, the smaller we appear to those who cannot fly.", author: "Friedrich Nietzsche", lang: "en" },
  { text: "All truly great thoughts are conceived while walking.", author: "Friedrich Nietzsche", lang: "en" },
  { text: "Life can only be understood backwards, but it must be lived forwards.", author: "Søren Kierkegaard", lang: "en" },
  { text: "Anxiety is the dizziness of freedom.", author: "Søren Kierkegaard", lang: "en" },
  { text: "The most common form of despair is not being who you are.", author: "Søren Kierkegaard", lang: "en" },
  { text: "To dare is to lose one's footing momentarily. Not to dare is to lose oneself.", author: "Søren Kierkegaard", lang: "en" },
  { text: "Purity of heart is to will one thing.", author: "Søren Kierkegaard", lang: "en" },
  { text: "Face the facts of being what you are, for that is what changes what you are.", author: "Søren Kierkegaard", lang: "en" },
  { text: "A man can do what he wills, but he cannot will what he wills.", author: "Arthur Schopenhauer", lang: "en" },
  { text: "Talent hits a target no one else can hit; genius hits a target no one else can see.", author: "Arthur Schopenhauer", lang: "en" },
  { text: "The two enemies of human happiness are pain and boredom.", author: "Arthur Schopenhauer", lang: "en" },
  { text: "Compassion is the basis of morality.", author: "Arthur Schopenhauer", lang: "en" },
  { text: "Science is organised knowledge. Wisdom is organised life.", author: "Immanuel Kant", lang: "en" },
  { text: "Act only according to that maxim whereby you can at the same time will that it should become a universal law.", author: "Immanuel Kant", lang: "en" },
  { text: "All of humanity's problems stem from man's inability to sit quietly in a room alone.", author: "Blaise Pascal", lang: "en" },
  { text: "The heart has its reasons of which reason knows nothing.", author: "Blaise Pascal", lang: "en" },
  { text: "I have made this letter longer than usual because I lack the time to make it shorter.", author: "Blaise Pascal", lang: "en" },
  { text: "The greatest thing in the world is to know how to belong to oneself.", author: "Michel de Montaigne", lang: "en" },
  { text: "The greatest part of the world's troubles come from questions of grammar.", author: "Michel de Montaigne", lang: "en" },
  { text: "It is not enough to have a good mind; the main thing is to use it well.", author: "René Descartes", lang: "en" },
  { text: "The reading of all good books is like a conversation with the finest minds of past centuries.", author: "René Descartes", lang: "en" },
  { text: "The perfect is the enemy of the good.", author: "Voltaire", lang: "en" },
  { text: "No problem can withstand the assault of sustained thinking.", author: "Voltaire", lang: "en" },
  { text: "Peace is not an absence of war; it is a virtue, a state of mind, a disposition for benevolence.", author: "Baruch Spinoza", lang: "en" },
  { text: "We are more interested in making others believe we are happy than in trying to be happy ourselves.", author: "François de La Rochefoucauld", lang: "en" },
  { text: "Everyone complains of his memory, and no one complains of his judgement.", author: "François de La Rochefoucauld", lang: "en" },
  { text: "The chains of habit are too weak to be felt until they are too strong to be broken.", author: "Samuel Johnson", lang: "en" },
  { text: "Great works are performed not by strength but by perseverance.", author: "Samuel Johnson", lang: "en" },
  { text: "Nothing will ever be attempted if all possible objections must be first overcome.", author: "Samuel Johnson", lang: "en" },
  { text: "He who has provoked the shaft of wit cannot complain that he smarts from it.", author: "Samuel Johnson", lang: "en" },
  { text: "I can resist everything except temptation.", author: "Oscar Wilde", lang: "en" },
  { text: "Experience is simply the name we give our mistakes.", author: "Oscar Wilde", lang: "en" },
  { text: "Anything worth doing is worth doing badly.", author: "G. K. Chesterton", lang: "en" },
  { text: "The safest road to hell is the gradual one — the gentle slope, soft underfoot, without sudden turnings, without milestones, without signposts.", author: "C. S. Lewis", lang: "en" },
  { text: "Courage is not simply one of the virtues, but the form of every virtue at the testing point.", author: "C. S. Lewis", lang: "en" },
  { text: "All we have to decide is what to do with the time that is given us.", author: "J. R. R. Tolkien", lang: "en" },
  { text: "Not all those who wander are lost.", author: "J. R. R. Tolkien", lang: "en" },
  { text: "Above all, do not lie to yourself. The man who lies to himself and listens to his own lie comes to a point that he cannot distinguish the truth within him.", author: "Fyodor Dostoevsky", lang: "en" },
  { text: "Man is a creature that can get accustomed to anything.", author: "Fyodor Dostoevsky", lang: "en" },
  { text: "The mystery of human existence lies not in just staying alive, but in finding something to live for.", author: "Fyodor Dostoevsky", lang: "en" },
  { text: "Taking a new step, uttering a new word, is what people fear most.", author: "Fyodor Dostoevsky", lang: "en" },
  { text: "To go wrong in one's own way is better than to go right in someone else's.", author: "Fyodor Dostoevsky", lang: "en" },
  { text: "Pain and suffering are always inevitable for a large intelligence and a deep heart.", author: "Fyodor Dostoevsky", lang: "en" },
  { text: "Everyone thinks of changing the world, but no one thinks of changing himself.", author: "Leo Tolstoy", lang: "en" },
  { text: "The two most powerful warriors are patience and time.", author: "Leo Tolstoy", lang: "en" },
  { text: "If you want to be happy, be.", author: "Leo Tolstoy", lang: "en" },
  { text: "There is no greatness where there is not simplicity, goodness and truth.", author: "Leo Tolstoy", lang: "en" },
  { text: "Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.", author: "Antoine de Saint-Exupéry", lang: "en" },
  { text: "As for the future, your task is not to foresee it, but to enable it.", author: "Antoine de Saint-Exupéry", lang: "en" },
  { text: "Even the darkest night will end and the sun will rise.", author: "Victor Hugo", lang: "en" },
  { text: "He who every morning plans the transactions of the day and follows out that plan carries a thread that will guide him through the labyrinth of the most busy life.", author: "Victor Hugo", lang: "en" },
  { text: "Habit is overcome by habit.", author: "Thomas à Kempis", lang: "en" },
  { text: "Patience is the companion of wisdom.", author: "Saint Augustine", lang: "en" },
  { text: "Do you wish to rise? Begin by descending.", author: "Saint Augustine", lang: "en" },
  { text: "Victory belongs to the most persevering.", author: "Napoleon Bonaparte", lang: "en" },
  { text: "The truest wisdom is a resolute determination.", author: "Napoleon Bonaparte", lang: "en" },
  { text: "The secret of success is constancy of purpose.", author: "Benjamin Disraeli", lang: "en" },
  { text: "Action may not always bring happiness, but there is no happiness without action.", author: "Benjamin Disraeli", lang: "en" },

  // --- American letters and history ---
  { text: "Nothing great was ever achieved without enthusiasm.", author: "Ralph Waldo Emerson", lang: "en" },
  { text: "Self-trust is the first secret of success.", author: "Ralph Waldo Emerson", lang: "en" },
  { text: "That which we persist in doing becomes easier — not that the nature of the task has changed, but our ability to do has increased.", author: "Ralph Waldo Emerson", lang: "en" },
  { text: "A man is what he thinks about all day long.", author: "Ralph Waldo Emerson", lang: "en" },
  { text: "The first wealth is health.", author: "Ralph Waldo Emerson", lang: "en" },
  { text: "Every man I meet is my master in some point, and in that I learn from him.", author: "Ralph Waldo Emerson", lang: "en" },
  { text: "Finish each day and be done with it. You have done what you could.", author: "Ralph Waldo Emerson", lang: "en" },
  { text: "Character is higher than intellect.", author: "Ralph Waldo Emerson", lang: "en" },
  { text: "The years teach much which the days never know.", author: "Ralph Waldo Emerson", lang: "en" },
  { text: "Whatever course you decide upon, there is always someone to tell you that you are wrong.", author: "Ralph Waldo Emerson", lang: "en" },
  { text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Henry Stanley Haskins", lang: "en" },
  { text: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau", lang: "en" },
  { text: "The price of anything is the amount of life you exchange for it.", author: "Henry David Thoreau", lang: "en" },
  { text: "It is not what you look at that matters, it is what you see.", author: "Henry David Thoreau", lang: "en" },
  { text: "As a single footstep will not make a path on the earth, so a single thought will not make a pathway in the mind.", author: "Henry David Thoreau", lang: "en" },
  { text: "Things do not change; we change.", author: "Henry David Thoreau", lang: "en" },
  { text: "I know of no more encouraging fact than the unquestionable ability of man to elevate his life by conscious endeavour.", author: "Henry David Thoreau", lang: "en" },
  { text: "The mass of men lead lives of quiet desperation.", author: "Henry David Thoreau", lang: "en" },
  { text: "Live in each season as it passes.", author: "Henry David Thoreau", lang: "en" },
  { text: "Habit is habit, and not to be flung out of the window by any man, but coaxed downstairs a step at a time.", author: "Mark Twain", lang: "en" },
  { text: "It is easier to stay out than get out.", author: "Mark Twain", lang: "en" },
  { text: "Courage is resistance to fear, mastery of fear — not absence of fear.", author: "Mark Twain", lang: "en" },
  { text: "The man who does not read has no advantage over the man who cannot read.", author: "Mark Twain", lang: "en" },
  { text: "Do the right thing. It will gratify some people and astonish the rest.", author: "Mark Twain", lang: "en" },
  { text: "Whenever you find yourself on the side of the majority, it is time to pause and reflect.", author: "Mark Twain", lang: "en" },
  { text: "Giving up smoking is the easiest thing in the world. I know, because I have done it thousands of times.", author: "Mark Twain", lang: "en" },
  { text: "Lost time is never found again.", author: "Benjamin Franklin", lang: "en" },
  { text: "Do not squander time, for that is the stuff life is made of.", author: "Benjamin Franklin", lang: "en" },
  { text: "Early to bed and early to rise makes a man healthy, wealthy and wise.", author: "Benjamin Franklin", lang: "en" },
  { text: "Well done is better than well said.", author: "Benjamin Franklin", lang: "en" },
  { text: "Energy and persistence conquer all things.", author: "Benjamin Franklin", lang: "en" },
  { text: "He that can have patience can have what he will.", author: "Benjamin Franklin", lang: "en" },
  { text: "By failing to prepare, you are preparing to fail.", author: "Benjamin Franklin", lang: "en" },
  { text: "There are no gains without pains.", author: "Benjamin Franklin", lang: "en" },
  { text: "What we obtain too cheap, we esteem too lightly.", author: "Thomas Paine", lang: "en" },
  { text: "The harder the conflict, the more glorious the triumph.", author: "Thomas Paine", lang: "en" },
  { text: "I am a slow walker, but I never walk back.", author: "Abraham Lincoln", lang: "en" },
  { text: "Nearly all men can stand adversity, but if you want to test a man's character, give him power.", author: "Abraham Lincoln", lang: "en" },
  { text: "Character is like a tree and reputation like its shadow. The shadow is what we think of it; the tree is the real thing.", author: "Abraham Lincoln", lang: "en" },
  { text: "Whatever you are, be a good one.", author: "Abraham Lincoln", lang: "en" },
  { text: "If there is no struggle, there is no progress.", author: "Frederick Douglass", lang: "en" },
  { text: "I prayed for twenty years but received no answer until I prayed with my legs.", author: "Frederick Douglass", lang: "en" },
  { text: "Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome.", author: "Booker T. Washington", lang: "en" },
  { text: "Nothing ever comes to one that is worth having except as a result of hard work.", author: "Booker T. Washington", lang: "en" },
  { text: "Excellence is to do a common thing in an uncommon way.", author: "Booker T. Washington", lang: "en" },
  { text: "It is not the critic who counts. The credit belongs to the man who is actually in the arena, whose face is marred by dust and sweat and blood.", author: "Theodore Roosevelt", lang: "en" },
  { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt", lang: "en" },
  { text: "Nothing in the world is worth having or worth doing unless it means effort, pain, difficulty.", author: "Theodore Roosevelt", lang: "en" },
  { text: "Far better it is to dare mighty things, even though checkered by failure, than to rank with those poor spirits who neither enjoy much nor suffer much.", author: "Theodore Roosevelt", lang: "en" },
  { text: "Nothing in the world can take the place of persistence. Talent will not; genius will not; education will not. Persistence and determination alone are omnipotent.", author: "Calvin Coolidge", lang: "en" },
  { text: "Genius is one percent inspiration and ninety-nine percent perspiration.", author: "Thomas Edison", lang: "en" },
  { text: "I have not failed. I have just found ten thousand ways that will not work.", author: "Thomas Edison", lang: "en" },
  { text: "Our greatest weakness lies in giving up. The most certain way to succeed is always to try just one more time.", author: "Thomas Edison", lang: "en" },
  { text: "Many of life's failures are people who did not realise how close they were to success when they gave up.", author: "Thomas Edison", lang: "en" },
  { text: "Whether you think you can or you think you cannot, you are right.", author: "Henry Ford", lang: "en" },
  { text: "Failure is simply the opportunity to begin again, this time more intelligently.", author: "Henry Ford", lang: "en" },
  { text: "Obstacles are those frightful things you see when you take your eyes off your goal.", author: "Henry Ford", lang: "en" },
  { text: "Coming together is a beginning; keeping together is progress; working together is success.", author: "Henry Ford", lang: "en" },
  { text: "Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened.", author: "Helen Keller", lang: "en" },
  { text: "Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.", author: "Helen Keller", lang: "en" },
  { text: "You must do the thing you think you cannot do.", author: "Eleanor Roosevelt", lang: "en" },
  { text: "No one can make you feel inferior without your consent.", author: "Eleanor Roosevelt", lang: "en" },
  { text: "I am the master of my fate, I am the captain of my soul.", author: "William Ernest Henley", lang: "en" },
  { text: "The best way out is always through.", author: "Robert Frost", lang: "en" },
  { text: "In three words I can sum up everything I have learned about life: it goes on.", author: "Robert Frost", lang: "en" },
  { text: "The world breaks everyone, and afterward, many are strong at the broken places.", author: "Ernest Hemingway", lang: "en" },
  { text: "You may not control all the events that happen to you, but you can decide not to be reduced by them.", author: "Maya Angelou", lang: "en" },
  { text: "Nothing will work unless you do.", author: "Maya Angelou", lang: "en" },
  { text: "If you can force your heart and nerve and sinew to serve your turn long after they are gone, and so hold on when there is nothing in you except the Will which says to them: Hold on!", author: "Rudyard Kipling", lang: "en" },
  { text: "Fill the unforgiving minute with sixty seconds' worth of distance run.", author: "Rudyard Kipling", lang: "en" },
  { text: "Life shrinks or expands in proportion to one's courage.", author: "Anaïs Nin", lang: "en" },
  { text: "The worst enemy to creativity is self-doubt.", author: "Sylvia Plath", lang: "en" },
  { text: "The secret of change is to focus all of your energy not on fighting the old, but on building the new.", author: "Dan Millman", lang: "en" },

  // --- Twentieth century ---
  { text: "Everything can be taken from a man but one thing: the last of the human freedoms — to choose one's attitude in any given set of circumstances.", author: "Viktor E. Frankl", lang: "en" },
  { text: "When we are no longer able to change a situation, we are challenged to change ourselves.", author: "Viktor E. Frankl", lang: "en" },
  { text: "What is to give light must endure burning.", author: "Viktor E. Frankl", lang: "en" },
  { text: "Live as if you were living already for the second time and as if you had acted the first time as wrongly as you are about to act now.", author: "Viktor E. Frankl", lang: "en" },
  { text: "The greatest weapon against stress is our ability to choose one thought over another.", author: "William James", lang: "en" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James", lang: "en" },
  { text: "Nothing is so fatiguing as the eternal hanging on of an uncompleted task.", author: "William James", lang: "en" },
  { text: "Every smallest stroke of virtue or of vice leaves its never-so-little scar.", author: "William James", lang: "en" },
  { text: "The greatest discovery of my generation is that a human being can alter his life by altering his attitude.", author: "William James", lang: "en" },
  { text: "Until you make the unconscious conscious, it will direct your life and you will call it fate.", author: "Carl Jung", lang: "en" },
  { text: "Who looks outside, dreams; who looks inside, awakes.", author: "Carl Jung", lang: "en" },
  { text: "Everything that irritates us about others can lead us to an understanding of ourselves.", author: "Carl Jung", lang: "en" },
  { text: "The cave you fear to enter holds the treasure you seek.", author: "Joseph Campbell", lang: "en" },
  { text: "The privilege of a lifetime is being who you are.", author: "Joseph Campbell", lang: "en" },
  { text: "We must be willing to let go of the life we planned so as to have the life that is waiting for us.", author: "Joseph Campbell", lang: "en" },
  { text: "Never give in, never give in, never, never, never.", author: "Winston Churchill", lang: "en" },
  { text: "It is no use saying we are doing our best. You have got to succeed in doing what is necessary.", author: "Winston Churchill", lang: "en" },
  { text: "I have nothing to offer but blood, toil, tears and sweat.", author: "Winston Churchill", lang: "en" },
  { text: "We make a living by what we get, but we make a life by what we give.", author: "Winston Churchill", lang: "en" },
  { text: "Strength does not come from physical capacity. It comes from an indomitable will.", author: "Mahatma Gandhi", lang: "en" },
  { text: "If we could change ourselves, the tendencies in the world would also change.", author: "Mahatma Gandhi", lang: "en" },
  { text: "Live as if you were to die tomorrow. Learn as if you were to live forever.", author: "Mahatma Gandhi", lang: "en" },
  { text: "The future depends on what you do today.", author: "Mahatma Gandhi", lang: "en" },
  { text: "If you cannot fly then run, if you cannot run then walk, if you cannot walk then crawl, but whatever you do you have to keep moving forward.", author: "Martin Luther King Jr.", lang: "en" },
  { text: "The ultimate measure of a man is not where he stands in moments of comfort and convenience, but where he stands at times of challenge and controversy.", author: "Martin Luther King Jr.", lang: "en" },
  { text: "Faith is taking the first step even when you do not see the whole staircase.", author: "Martin Luther King Jr.", lang: "en" },
  { text: "There is no better than adversity. Every defeat, every heartbreak, every loss contains its own seed, its own lesson on how to improve your performance next time.", author: "Malcolm X", lang: "en" },
  { text: "The future belongs to those who prepare for it today.", author: "Malcolm X", lang: "en" },
  { text: "It always seems impossible until it is done.", author: "Nelson Mandela", lang: "en" },
  { text: "The greatest glory in living lies not in never falling, but in rising every time we fall.", author: "Nelson Mandela", lang: "en" },
  { text: "Do not judge me by my successes, judge me by how many times I fell down and got back up again.", author: "Nelson Mandela", lang: "en" },
  { text: "Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fear less.", author: "Marie Curie", lang: "en" },
  { text: "Life is like riding a bicycle. To keep your balance, you must keep moving.", author: "Albert Einstein", lang: "en" },
  { text: "Try not to become a man of success, but rather try to become a man of value.", author: "Albert Einstein", lang: "en" },
  { text: "It is not that I am so smart, it is just that I stay with problems longer.", author: "Albert Einstein", lang: "en" },
  { text: "The most difficult thing is the decision to act; the rest is merely tenacity.", author: "Amelia Earhart", lang: "en" },
  { text: "If you hear a voice within you saying you cannot paint, then by all means paint, and that voice will be silenced.", author: "Vincent van Gogh", lang: "en" },
  { text: "Great things are not done by impulse, but by a series of small things brought together.", author: "Vincent van Gogh", lang: "en" },
  { text: "Iron rusts from disuse; water loses its purity from stagnation. Even so does inaction sap the vigour of the mind.", author: "Leonardo da Vinci", lang: "en" },
  { text: "It is easier to resist at the beginning than at the end.", author: "Leonardo da Vinci", lang: "en" },
  { text: "The greater danger for most of us lies not in setting our aim too high and falling short, but in setting our aim too low and achieving our mark.", author: "Michelangelo", lang: "en" },
  { text: "I am still learning.", author: "Michelangelo", lang: "en" },
  { text: "Work is love made visible.", author: "Kahlil Gibran", lang: "en" },
  { text: "Your pain is the breaking of the shell that encloses your understanding.", author: "Kahlil Gibran", lang: "en" },

  // --- Modern practitioners ---
  { text: "The main thing is to keep the main thing the main thing.", author: "Stephen R. Covey", lang: "en" },
  { text: "Most of us spend too much time on what is urgent and not enough time on what is important.", author: "Stephen R. Covey", lang: "en" },
  { text: "Efficiency is doing things right; effectiveness is doing the right things.", author: "Peter Drucker", lang: "en" },
  { text: "What gets measured gets managed.", author: "Peter Drucker", lang: "en" },
  { text: "Someone is sitting in the shade today because someone planted a tree a long time ago.", author: "Warren Buffett", lang: "en" },
  { text: "The difference between successful people and really successful people is that really successful people say no to almost everything.", author: "Warren Buffett", lang: "en" },
  { text: "It takes twenty years to build a reputation and five minutes to ruin it.", author: "Warren Buffett", lang: "en" },
  { text: "Spend each day trying to be a little wiser than you were when you woke up.", author: "Charlie Munger", lang: "en" },
  { text: "Take a simple idea and take it seriously.", author: "Charlie Munger", lang: "en" },
  { text: "Discipline is the bridge between goals and accomplishment.", author: "Jim Rohn", lang: "en" },
  { text: "We must all suffer one of two things: the pain of discipline or the pain of regret.", author: "Jim Rohn", lang: "en" },
  { text: "You are the average of the five people you spend the most time with.", author: "Jim Rohn", lang: "en" },
  { text: "Success is nothing more than a few simple disciplines practised every day.", author: "Jim Rohn", lang: "en" },
  { text: "Do not wish it were easier; wish you were better.", author: "Jim Rohn", lang: "en" },
  { text: "Motivation is what gets you started. Habit is what keeps you going.", author: "Jim Rohn", lang: "en" },
  { text: "You do not have to be great to start, but you have to start to be great.", author: "Zig Ziglar", lang: "en" },
  { text: "People often say that motivation does not last. Well, neither does bathing — that is why we recommend it daily.", author: "Zig Ziglar", lang: "en" },
  { text: "Do not let what you cannot do interfere with what you can do.", author: "John Wooden", lang: "en" },
  { text: "The true test of a man's character is what he does when no one is watching.", author: "John Wooden", lang: "en" },
  { text: "Be more concerned with your character than your reputation, because your character is what you really are.", author: "John Wooden", lang: "en" },
  { text: "Make each day your masterpiece.", author: "John Wooden", lang: "en" },
  { text: "It is what you learn after you know it all that counts.", author: "John Wooden", lang: "en" },
  { text: "It is not whether you get knocked down; it is whether you get up.", author: "Vince Lombardi", lang: "en" },
  { text: "The only place success comes before work is in the dictionary.", author: "Vince Lombardi", lang: "en" },
  { text: "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack of will.", author: "Vince Lombardi", lang: "en" },
  { text: "It is not the will to win that matters — everyone has that. It is the will to prepare to win that matters.", author: "Paul Bear Bryant", lang: "en" },
  { text: "Patience, persistence and perspiration make an unbeatable combination for success.", author: "Napoleon Hill", lang: "en" },
  { text: "Whatever the mind can conceive and believe, it can achieve.", author: "Napoleon Hill", lang: "en" },
  { text: "Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no hope at all.", author: "Dale Carnegie", lang: "en" },
  { text: "Inaction breeds doubt and fear. Action breeds confidence and courage.", author: "Dale Carnegie", lang: "en" },
  { text: "I will persist until I succeed.", author: "Og Mandino", lang: "en" },
  { text: "Your time is limited, so do not waste it living someone else's life.", author: "Steve Jobs", lang: "en" },
  { text: "The only way to do great work is to love what you do.", author: "Steve Jobs", lang: "en" },
  { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs", lang: "en" },
  { text: "When something is important enough, you do it even if the odds are not in your favour.", author: "Elon Musk", lang: "en" },
  { text: "You will never fully convince someone that he is wrong; only reality can.", author: "Nassim Nicholas Taleb", lang: "en" },
  { text: "The three most harmful addictions are heroin, carbohydrates and a monthly salary.", author: "Nassim Nicholas Taleb", lang: "en" },
  { text: "Grit is passion and perseverance for very long-term goals.", author: "Angela Duckworth", lang: "en" },
  { text: "Enthusiasm is common. Endurance is rare.", author: "Angela Duckworth", lang: "en" },
  { text: "Becoming is better than being.", author: "Carol S. Dweck", lang: "en" },
  { text: "A person's success in life can usually be measured by the number of uncomfortable conversations he or she is willing to have.", author: "Tim Ferriss", lang: "en" },
  { text: "If you want to change the world, start off by making your bed.", author: "William H. McRaven", lang: "en" },
  { text: "Who you are, what you think, feel and do, what you love — is the sum of what you focus on.", author: "Winifred Gallagher", lang: "en" },
  { text: "Clarity about what matters provides clarity about what does not.", author: "Cal Newport", lang: "en" },
  { text: "Deep work is like a superpower in our increasingly competitive economy.", author: "Cal Newport", lang: "en" },
  { text: "If you do not produce, you will not thrive — no matter how skilled or talented you are.", author: "Cal Newport", lang: "en" },
  { text: "You do not rise to the level of your goals. You fall to the level of your systems.", author: "James Clear", lang: "en" },
  { text: "Every action you take is a vote for the type of person you wish to become.", author: "James Clear", lang: "en" },
  { text: "Habits are the compound interest of self-improvement.", author: "James Clear", lang: "en" },
  { text: "You should be far more concerned with your current trajectory than with your current results.", author: "James Clear", lang: "en" },
  { text: "Never miss twice.", author: "James Clear", lang: "en" },
  { text: "The most effective form of motivation is progress.", author: "James Clear", lang: "en" },
  { text: "Compare yourself to who you were yesterday, not to who someone else is today.", author: "Jordan B. Peterson", lang: "en" },
  { text: "Set your house in perfect order before you criticise the world.", author: "Jordan B. Peterson", lang: "en" },
  { text: "Pursue what is meaningful, not what is expedient.", author: "Jordan B. Peterson", lang: "en" },
  { text: "Tell the truth — or, at least, do not lie.", author: "Jordan B. Peterson", lang: "en" },
  { text: "Treat yourself like someone you are responsible for helping.", author: "Jordan B. Peterson", lang: "en" },
  { text: "Discipline equals freedom.", author: "Jocko Willink", lang: "en" },
  { text: "Do not count on motivation. Count on discipline.", author: "Jocko Willink", lang: "en" },
  { text: "Leaders must own everything in their world. There is no one else to blame.", author: "Jocko Willink", lang: "en" },
  { text: "You are in danger of living a life so comfortable and soft that you will die without ever realising your true potential.", author: "David Goggins", lang: "en" },
  { text: "The most important conversations you will ever have are the ones you will have with yourself.", author: "David Goggins", lang: "en" },
  { text: "Motivation comes and goes. When you are driven, whatever is in front of you will get destroyed.", author: "David Goggins", lang: "en" },
  { text: "The only way you gain mental toughness is to do things you are not happy doing.", author: "David Goggins", lang: "en" },
  { text: "Desire is a contract you make with yourself to be unhappy until you get what you want.", author: "Naval Ravikant", lang: "en" },
  { text: "A busy calendar and a busy mind will destroy your ability to create anything great.", author: "Naval Ravikant", lang: "en" },
  { text: "Happiness is a skill you develop and a choice you make.", author: "Naval Ravikant", lang: "en" },
  { text: "Play long-term games with long-term people.", author: "Naval Ravikant", lang: "en" },
  { text: "Read what you love until you love to read.", author: "Naval Ravikant", lang: "en" },
  { text: "Free education is abundant, all over the internet. It is the desire to learn that is scarce.", author: "Naval Ravikant", lang: "en" },
  { text: "We chase wealth, health and happiness in that order, but their importance is the reverse.", author: "Naval Ravikant", lang: "en" },

  // --- Athletes and fighters ---
  { text: "I hated every minute of training, but I said: do not quit. Suffer now and live the rest of your life as a champion.", author: "Muhammad Ali", lang: "en" },
  { text: "The fight is won or lost far away from witnesses — behind the lines, in the gym, and out there on the road, long before I dance under those lights.", author: "Muhammad Ali", lang: "en" },
  { text: "It is not the mountains ahead to climb that wear you out; it is the pebble in your shoe.", author: "Muhammad Ali", lang: "en" },
  { text: "Do not count the days, make the days count.", author: "Muhammad Ali", lang: "en" },
  { text: "Service to others is the rent you pay for your room here on earth.", author: "Muhammad Ali", lang: "en" },
  { text: "He who is not courageous enough to take risks will accomplish nothing in life.", author: "Muhammad Ali", lang: "en" },
  { text: "I am the greatest. I said that even before I knew I was.", author: "Muhammad Ali", lang: "en" },
  { text: "Great things come from hard work and perseverance. No excuses.", author: "Kobe Bryant", lang: "en" },
  { text: "If you are afraid to fail, then you are probably going to fail.", author: "Kobe Bryant", lang: "en" },
  { text: "Everything negative — pressure, challenges — is all an opportunity for me to rise.", author: "Kobe Bryant", lang: "en" },
  { text: "The moment you give up is the moment you let someone else win.", author: "Kobe Bryant", lang: "en" },
  { text: "I cannot relate to lazy people. We do not speak the same language.", author: "Kobe Bryant", lang: "en" },
  { text: "Rest at the end, not in the middle.", author: "Kobe Bryant", lang: "en" },
  { text: "I have missed more than nine thousand shots in my career. I have failed over and over again in my life — and that is why I succeed.", author: "Michael Jordan", lang: "en" },
  { text: "I can accept failure, everyone fails at something. But I cannot accept not trying.", author: "Michael Jordan", lang: "en" },
  { text: "Some people want it to happen, some wish it would happen, others make it happen.", author: "Michael Jordan", lang: "en" },
  { text: "If you run into a wall, do not turn around and give up. Figure out how to climb it, go through it, or work around it.", author: "Michael Jordan", lang: "en" },
  { text: "You have to expect things of yourself before you can do them.", author: "Michael Jordan", lang: "en" },
  { text: "Strength does not come from winning. Your struggles develop your strengths.", author: "Arnold Schwarzenegger", lang: "en" },
  { text: "The last three or four repetitions is what makes the muscle grow.", author: "Arnold Schwarzenegger", lang: "en" },
  { text: "The mind is the limit. As long as the mind can envision that you can do something, you can do it.", author: "Arnold Schwarzenegger", lang: "en" },
  { text: "The worst thing I can be is the same as everybody else.", author: "Arnold Schwarzenegger", lang: "en" },
  { text: "Everyone has a plan until they get punched in the mouth.", author: "Mike Tyson", lang: "en" },
  { text: "Discipline is doing what you hate to do but doing it like you love it.", author: "Mike Tyson", lang: "en" },
  { text: "You miss one hundred percent of the shots you do not take.", author: "Wayne Gretzky", lang: "en" },
  { text: "Success is no accident. It is hard work, perseverance, learning, studying, sacrifice and most of all, love of what you are doing.", author: "Pelé", lang: "en" },
  { text: "Talent without working hard is nothing.", author: "Cristiano Ronaldo", lang: "en" },
  { text: "You have to fight to reach your dream. You have to sacrifice and work hard for it.", author: "Lionel Messi", lang: "en" },
  { text: "I trained four years to run nine seconds.", author: "Usain Bolt", lang: "en" },
  { text: "Luck has nothing to do with it, because I have spent many, many hours, countless hours, on the court working for my one moment in time.", author: "Serena Williams", lang: "en" },
  { text: "You cannot put a limit on anything. The more you dream, the farther you get.", author: "Michael Phelps", lang: "en" },
  { text: "There is no talent here, this is hard work. This is an obsession.", author: "Conor McGregor", lang: "en" },
  { text: "When you want to succeed as badly as you want to breathe, then you will be successful.", author: "Eric Thomas", lang: "en" },

  // --- Türkçe ---
  { text: "Hayatta en hakiki mürşit ilimdir.", author: "Mustafa Kemal Atatürk", lang: "tr" },
  { text: "Muhtaç olduğun kudret, damarlarındaki asil kanda mevcuttur.", author: "Mustafa Kemal Atatürk", lang: "tr" },
  { text: "Ben sporcunun zeki, çevik ve aynı zamanda ahlaklısını severim.", author: "Mustafa Kemal Atatürk", lang: "tr" },
  { text: "Türk, öğün, çalış, güven.", author: "Mustafa Kemal Atatürk", lang: "tr" },
  { text: "Beni görmek demek mutlaka yüzümü görmek değildir. Benim fikirlerimi, benim duygularımı anlıyorsanız ve hissediyorsanız bu kâfidir.", author: "Mustafa Kemal Atatürk", lang: "tr" },
  { text: "En büyük savaş, cahilliğe karşı yapılan savaştır.", author: "Mustafa Kemal Atatürk", lang: "tr" },
  { text: "Umutsuz durumlar yoktur, umutsuz insanlar vardır. Ben hiçbir zaman umudumu yitirmedim.", author: "Mustafa Kemal Atatürk", lang: "tr" },
  { text: "Zafer, zafer benimdir diyebilenindir. Başarı ise başaracağım diye başlayarak sonunda başardım diyebilenindir.", author: "Mustafa Kemal Atatürk", lang: "tr" },
  { text: "Hattı müdafaa yoktur, sathı müdafaa vardır. O satıh bütün vatandır.", author: "Mustafa Kemal Atatürk", lang: "tr" },
  { text: "Öğretmenler! Yeni nesil sizin eseriniz olacaktır.", author: "Mustafa Kemal Atatürk", lang: "tr" },
  { text: "Sanatsız kalan bir milletin hayat damarlarından biri kopmuş demektir.", author: "Mustafa Kemal Atatürk", lang: "tr" },
  { text: "Egemenlik verilmez, alınır.", author: "Mustafa Kemal Atatürk", lang: "tr" },
  { text: "Ya olduğun gibi görün, ya göründüğün gibi ol.", author: "Mevlânâ Celâleddîn-i Rûmî", lang: "tr" },
  { text: "Dün dünde kaldı cancağızım, bugün yeni şeyler söylemek lazım.", author: "Mevlânâ Celâleddîn-i Rûmî", lang: "tr" },
  { text: "Hamdım, piştim, yandım.", author: "Mevlânâ Celâleddîn-i Rûmî", lang: "tr" },
  { text: "İlim ilim bilmektir, ilim kendin bilmektir; sen kendini bilmezsin, ya nice okumaktır.", author: "Yunus Emre", lang: "tr" },
  { text: "Bir ben vardır bende benden içeri.", author: "Yunus Emre", lang: "tr" },
  { text: "Sevelim sevilelim, dünya kimseye kalmaz.", author: "Yunus Emre", lang: "tr" },
  { text: "Gelin tanış olalım, işi kolay kılalım.", author: "Yunus Emre", lang: "tr" },
  { text: "Söz ola kese savaşı, söz ola kestire başı; söz ola ağulu aşı bal ile yağ ede bir söz.", author: "Yunus Emre", lang: "tr" },
  { text: "Dervişlik dedikleri hırka ile taç değil; gönlün derviş eyleyen hırkaya muhtaç değil.", author: "Yunus Emre", lang: "tr" },
  { text: "Ben gelmedim dava için, benim işim sevi için.", author: "Yunus Emre", lang: "tr" },
  { text: "Mal sahibi, mülk sahibi; hani bunun ilk sahibi?", author: "Yunus Emre", lang: "tr" },
  { text: "Atiyi karanlık görerek azmi bırakmak... Alçak bir ölüm varsa, eminim, budur ancak.", author: "Mehmet Âkif Ersoy", lang: "tr" },
  { text: "Ye's öyle bataktır ki düşersen boğulursun. Ümmîde sarıl sımsıkı, seyret ne olursun!", author: "Mehmet Âkif Ersoy", lang: "tr" },
  { text: "Bekayı hak tanıyan sa'yi bir vazife bilir; çalış çalış ki beka sa'y olursa hak edilir.", author: "Mehmet Âkif Ersoy", lang: "tr" },
  { text: "Sahipsiz olan memleketin batması haktır; sen sahip olursan bu vatan batmayacaktır.", author: "Mehmet Âkif Ersoy", lang: "tr" },
  { text: "Kim kazanmazsa bu dünyada bir ekmek parası, dostunun yüz karası, düşmanının maskarası.", author: "Mehmet Âkif Ersoy", lang: "tr" },
  { text: "Ne irfandır veren ahlâka yükseklik, ne vicdandır; fazilet hissi insanlarda Allah korkusundandır.", author: "Mehmet Âkif Ersoy", lang: "tr" },
  { text: "Zulmü alkışlayamam, zalimi asla sevemem; gelenin keyfi için geçmişe kalkıp sövemem.", author: "Mehmet Âkif Ersoy", lang: "tr" },
  { text: "Girmeden tefrika bir millete, düşman giremez; toplu vurdukça yürekler, onu top sindiremez.", author: "Mehmet Âkif Ersoy", lang: "tr" },
  { text: "Kanayan bir yara gördüm mü yanar tâ ciğerim.", author: "Mehmet Âkif Ersoy", lang: "tr" },
  { text: "Eline, diline, beline sahip ol.", author: "Hacı Bektâş-ı Velî", lang: "tr" },
  { text: "İlimden gidilmeyen yolun sonu karanlıktır.", author: "Hacı Bektâş-ı Velî", lang: "tr" },
  { text: "Düşünce karanlığına ışık tutanlara ne mutlu.", author: "Hacı Bektâş-ı Velî", lang: "tr" },
  { text: "Nefsine ağır geleni kimseye tatbik etme.", author: "Hacı Bektâş-ı Velî", lang: "tr" },
  { text: "Bir olalım, iri olalım, diri olalım.", author: "Hacı Bektâş-ı Velî", lang: "tr" },
  { text: "Hiçbir milleti ve insanı ayıplama.", author: "Hacı Bektâş-ı Velî", lang: "tr" },
  { text: "Âyinesi iştir kişinin lafa bakılmaz; şahsın görünür rütbe-i aklı eserinde.", author: "Ziya Paşa", lang: "tr" },
  { text: "İnsana sadakat yaraşır görse de ikrah; yardımcısıdır doğruların Hazret-i Allah.", author: "Ziya Paşa", lang: "tr" },
  { text: "Durun kalabalıklar, bu cadde çıkmaz sokak!", author: "Necip Fazıl Kısakürek", lang: "tr" },
  { text: "Tam otuz yıl saatim işlemiş, ben durmuşum; gökyüzünden habersiz uçurtma uçurmuşum.", author: "Necip Fazıl Kısakürek", lang: "tr" },
  { text: "Anladım işi, sanat Allah'ı aramakmış; marifet bu, gerisi yalnız çelik-çomakmış.", author: "Necip Fazıl Kısakürek", lang: "tr" },
  { text: "Yaşamak bir ağaç gibi tek ve hür ve bir orman gibi kardeşçesine.", author: "Nâzım Hikmet", lang: "tr" },
  { text: "En güzel deniz henüz gidilmemiş olanıdır. En güzel çocuk henüz büyümedi. En güzel günlerimiz henüz yaşamadıklarımız.", author: "Nâzım Hikmet", lang: "tr" },
  { text: "Yaşamayı ciddiye alacaksın, yani o kadar, öylesine ki, mesela ellerin bağlı arkadan, sırtın duvarda.", author: "Nâzım Hikmet", lang: "tr" },
  { text: "Uzun ince bir yoldayım, gidiyorum gündüz gece.", author: "Âşık Veysel", lang: "tr" },
  { text: "Benim sadık yârim kara topraktır.", author: "Âşık Veysel", lang: "tr" },
  { text: "Hoşça bak zâtına kim zübde-i âlemsin sen; merdüm-i dîde-i ekvân olan âdemsin sen.", author: "Şeyh Galib", lang: "tr" },
  { text: "Aşk imiş her ne var âlemde, ilm bir kîl ü kâl imiş ancak.", author: "Fuzûlî", lang: "tr" },
  { text: "Halk içinde muteber bir nesne yok devlet gibi; olmaya devlet cihanda bir nefes sıhhat gibi.", author: "Muhibbî (Kanûnî Sultan Süleyman)", lang: "tr" },
  { text: "Padişah-ı âlem olmak bir kuru kavga imiş; bir veliye bende olmak cümleden âlâ imiş.", author: "Yavuz Sultan Selim", lang: "tr" },
  { text: "Kamus namustur.", author: "Cemil Meriç", lang: "tr" },
  { text: "Damlaya damlaya göl olur.", author: "Türk atasözü", lang: "tr" },
  { text: "Sabreden derviş muradına ermiş.", author: "Türk atasözü", lang: "tr" },
  { text: "Ağaç yaşken eğilir.", author: "Türk atasözü", lang: "tr" },
  { text: "Bugünün işini yarına bırakma.", author: "Türk atasözü", lang: "tr" },
  { text: "İşleyen demir pas tutmaz.", author: "Türk atasözü", lang: "tr" },
  { text: "Emek olmadan yemek olmaz.", author: "Türk atasözü", lang: "tr" },
  { text: "Acele işe şeytan karışır.", author: "Türk atasözü", lang: "tr" },
  { text: "Sakla samanı, gelir zamanı.", author: "Türk atasözü", lang: "tr" },
  { text: "Ne ekersen onu biçersin.", author: "Türk atasözü", lang: "tr" },
  { text: "Son pişmanlık fayda etmez.", author: "Türk atasözü", lang: "tr" },
  { text: "Öfkeyle kalkan zararla oturur.", author: "Türk atasözü", lang: "tr" },
  { text: "Sabrın sonu selamettir.", author: "Türk atasözü", lang: "tr" },
  { text: "Zararın neresinden dönülse kârdır.", author: "Türk atasözü", lang: "tr" },
  { text: "Bir musibet bin nasihatten yeğdir.", author: "Türk atasözü", lang: "tr" },
  { text: "Yiğit lafının eridir.", author: "Türk atasözü", lang: "tr" },
  { text: "Söz gümüşse sükût altındır.", author: "Türk atasözü", lang: "tr" },
  { text: "Az söyle, çok dinle.", author: "Türk atasözü", lang: "tr" },
  { text: "Erken kalkan yol alır.", author: "Türk atasözü", lang: "tr" },
  { text: "Gülü seven dikenine katlanır.", author: "Türk atasözü", lang: "tr" },
  { text: "İnsan yedisinde ne ise yetmişinde odur.", author: "Türk atasözü", lang: "tr" },
  { text: "Alet işler, el övünür.", author: "Türk atasözü", lang: "tr" },
  { text: "Kervan yolda düzülür.", author: "Türk atasözü", lang: "tr" },
  { text: "Ağır ol, batman gelesin.", author: "Türk atasözü", lang: "tr" },
  { text: "Keskin sirke küpüne zarar.", author: "Türk atasözü", lang: "tr" },
  { text: "Rüzgâr eken fırtına biçer.", author: "Türk atasözü", lang: "tr" },
  { text: "Sona kalan dona kalır.", author: "Türk atasözü", lang: "tr" },
  { text: "İki karpuz bir koltuğa sığmaz.", author: "Türk atasözü", lang: "tr" },
  { text: "Görünen köy kılavuz istemez.", author: "Türk atasözü", lang: "tr" },
  { text: "Tembele iş buyur, sana akıl öğretsin.", author: "Türk atasözü", lang: "tr" },
  { text: "Ak akçe kara gün içindir.", author: "Türk atasözü", lang: "tr" },
  { text: "Sabır acıdır, meyvesi tatlıdır.", author: "Türk atasözü", lang: "tr" },
  { text: "Herkes kendi kapısının önünü süpürse, mahalle tertemiz olur.", author: "Türk atasözü", lang: "tr" },
  { text: "Ummadığın taş baş yarar.", author: "Türk atasözü", lang: "tr" },
  { text: "Dost kara günde belli olur.", author: "Türk atasözü", lang: "tr" },
  { text: "Yuvarlanan taş yosun tutmaz.", author: "Türk atasözü", lang: "tr" },
  { text: "Bir elin nesi var, iki elin sesi var.", author: "Türk atasözü", lang: "tr" },
  { text: "Çok yaşayan bilmez, çok gezen bilir.", author: "Türk atasözü", lang: "tr" },
  { text: "Zorla güzellik olmaz.", author: "Türk atasözü", lang: "tr" },
  { text: "El elden üstündür.", author: "Türk atasözü", lang: "tr" },
  { text: "Sürüden ayrılanı kurt kapar.", author: "Türk atasözü", lang: "tr" },
  { text: "Her şeyin yenisi, dostun eskisi.", author: "Türk atasözü", lang: "tr" },
  { text: "Bin bilsen de bir bilene danış.", author: "Türk atasözü", lang: "tr" },
  { text: "İşten artmaz, dişten artar.", author: "Türk atasözü", lang: "tr" },
  { text: "Taşıma su ile değirmen dönmez.", author: "Türk atasözü", lang: "tr" },
  { text: "Su akarken testiyi doldurmak gerek.", author: "Türk atasözü", lang: "tr" },
  { text: "İnsanın alacası içinde, hayvanın alacası dışında.", author: "Türk atasözü", lang: "tr" },
];

export const MILESTONES: { days: number; title: string; note: string }[] = [
  { days: 1,   title: "Day One",       note: "The decision is made. Withdrawal starts — that discomfort is the addiction dying, not you." },
  { days: 3,   title: "The Spike",     note: "Urges usually peak around now. Survive these 72 hours and they start losing power." },
  { days: 7,   title: "One Week",      note: "Sleep deepens, energy climbs. Your dopamine system is noticing the silence." },
  { days: 14,  title: "Two Weeks",     note: "Brain fog lifts. Focus and eye contact come back. Flatline may hit — it's healing, not failure." },
  { days: 30,  title: "One Month",     note: "Dopamine sensitivity measurably recovering. Normal life starts feeling good again." },
  { days: 60,  title: "Two Months",    note: "New default installed. Triggers that owned you now just pass by." },
  { days: 90,  title: "The Reboot",    note: "The classic benchmark: receptor density largely restored. You are running on a rebuilt brain." },
  { days: 180, title: "Half a Year",   note: "This is no longer a challenge. It's who you are." },
  { days: 365, title: "One Year",      note: "Free. The person who started this streak wouldn't recognize you." },
];

export const PANIC_LINES: string[] = [
  "STOP. This urge is a wave — it peaks, then it dies. Ride it out.",
  "You are ten minutes of discomfort away from keeping everything. That's the whole price.",
  "Bu his en fazla 10 dakika sürer. Pişmanlık günlerce.",
  "Close the tabs. Stand up. Cold water on your face. NOW.",
  "The version of you that gives in doesn't get to complain about his life.",
  "Your brain is screaming for a drug. You are not your brain's errand boy.",
  "Şu an vazgeçersen, yarın aynaya nasıl bakacaksın?",
  "Nothing you're about to see is worth what you're about to lose.",
  "You've been here before. You know exactly how the regret tastes. Skip it.",
  "Breathe. The counter upstairs is still running. Keep it running.",
  "Dayan. Bu dalga geçince daha güçlü olacaksın. Her seferinde daha güçlü.",
  "Do twenty push-ups instead. Anger beats urge. Move.",
];
