// Curated couple questions, EN + TR. One per day, chosen deterministically by
// date — both of you answer blind, answers reveal together. Append freely;
// the daily pick stays stable for past days because answers store their
// question_idx.

export interface ZuyaQuestion {
  en: string;
  tr: string;
}

export const ZUYA_QUESTIONS: ZuyaQuestion[] = [
  { en: "What's a memory of us you replay the most?", tr: "En çok hangi anımızı tekrar tekrar hatırlıyorsun?" },
  { en: "What did you think the first time you saw me?", tr: "Beni ilk gördüğünde ne düşündün?" },
  { en: "What's one small thing I do that makes you feel loved?", tr: "Yaptığım hangi küçük şey sana sevildiğini hissettiriyor?" },
  { en: "Where should we travel together next?", tr: "Bir sonraki seyahatimiz nereye olmalı?" },
  { en: "What song will always remind you of us?", tr: "Hangi şarkı sana hep bizi hatırlatacak?" },
  { en: "What's your favorite photo of us, and why?", tr: "En sevdiğin fotoğrafımız hangisi, neden?" },
  { en: "If we had a whole free day tomorrow, how would we spend it?", tr: "Yarın tamamen boş bir günümüz olsa nasıl geçirirdik?" },
  { en: "What's something I taught you without realizing?", tr: "Farkında olmadan sana ne öğrettim?" },
  { en: "What meal should we learn to cook together?", tr: "Birlikte hangi yemeği yapmayı öğrenmeliyiz?" },
  { en: "When did you first realize you loved me?", tr: "Beni sevdiğini ilk ne zaman anladın?" },
  { en: "What's a dream you've never told me about?", tr: "Bana hiç anlatmadığın bir hayalin var mı?" },
  { en: "What do you hope we're doing ten years from now?", tr: "On yıl sonra ne yapıyor olmamızı umuyorsun?" },
  { en: "What's the funniest thing that's happened to us?", tr: "Başımıza gelen en komik şey neydi?" },
  { en: "Which of my habits secretly makes you smile?", tr: "Hangi huyum seni gizli gizli gülümsetiyor?" },
  { en: "What's the best gift I've ever given you?", tr: "Sana verdiğim en güzel hediye neydi?" },
  { en: "What would our perfect lazy Sunday look like?", tr: "Mükemmel tembel pazarımız nasıl olurdu?" },
  { en: "What's one thing you want us to try this month?", tr: "Bu ay birlikte denememizi istediğin bir şey?" },
  { en: "What smell or taste reminds you of me?", tr: "Hangi koku ya da tat sana beni hatırlatıyor?" },
  { en: "What's your favorite thing about how we argue and make up?", tr: "Tartışıp barışma şeklimizde en sevdiğin şey ne?" },
  { en: "If you could relive one of our dates, which one?", tr: "Buluşmalarımızdan birini yeniden yaşayabilsen hangisi olurdu?" },
  { en: "What are you most proud of me for?", tr: "Benimle en çok ne için gurur duyuyorsun?" },
  { en: "What's a fear you feel safe telling me?", tr: "Bana söylemekte güvende hissettiğin bir korkun var mı?" },
  { en: "What nickname of ours do you love the most?", tr: "Birbirimize taktığımız isimlerden en sevdiğin hangisi?" },
  { en: "What should we do more of as a couple?", tr: "Çift olarak neyi daha çok yapmalıyız?" },
  { en: "What's the most beautiful place we've been together?", tr: "Birlikte gittiğimiz en güzel yer neresiydi?" },
  { en: "What movie should we watch curled up this week?", tr: "Bu hafta sarılıp hangi filmi izleyelim?" },
  { en: "What's something new you learned about me recently?", tr: "Son zamanlarda benim hakkımda öğrendiğin yeni bir şey?" },
  { en: "If we wrote a book about us, what would its title be?", tr: "Bizim hikâyemizi bir kitap yapsak adı ne olurdu?" },
  { en: "What tiny everyday moment with me do you treasure?", tr: "Benimle geçen hangi küçük gündelik anı çok seviyorsun?" },
  { en: "What's your favorite way I say your name?", tr: "Adını söyleyiş şekillerimden en sevdiğin hangisi?" },
  { en: "Which city fits us best, and why?", tr: "Bize en çok hangi şehir yakışıyor, neden?" },
  { en: "What's one promise you want us to make each other?", tr: "Birbirimize vermemizi istediğin bir söz?" },
  { en: "When do you feel closest to me?", tr: "Kendini bana en yakın ne zaman hissediyorsun?" },
  { en: "What's a talent of mine you wish you had?", tr: "Bende olup sende de olsun istediğin bir yetenek?" },
  { en: "What tradition should we start, just the two of us?", tr: "Sadece ikimize ait hangi geleneği başlatalım?" },
  { en: "What did you tell your friends after our first date?", tr: "İlk buluşmamızdan sonra arkadaşlarına ne anlattın?" },
  { en: "What's the hardest thing we've gotten through together?", tr: "Birlikte atlattığımız en zor şey neydi?" },
  { en: "What outfit of mine do you love seeing me in?", tr: "Beni hangi kıyafetimle görmeyi seviyorsun?" },
  { en: "If we could teleport somewhere right now, where?", tr: "Şu an bir yere ışınlanabilseydik nereye giderdik?" },
  { en: "What's something silly we do that you'd never tell anyone?", tr: "Kimseye anlatmayacağın, ikimize ait saçma bir şey?" },
  { en: "What do I do when I think no one's watching that you find cute?", tr: "Kimse bakmıyor sanırken yaptığım hangi şeyi tatlı buluyorsun?" },
  { en: "What's your favorite conversation we've ever had?", tr: "Şimdiye kadarki en sevdiğin sohbetimiz hangisiydi?" },
  { en: "What would you cook for me if you had to impress me tonight?", tr: "Bu akşam beni etkilemen gerekse ne pişirirdin?" },
  { en: "What's one way I've changed you for the better?", tr: "Seni hangi konuda daha iyi biri yaptım?" },
  { en: "What pet should we get someday, and what would we name it?", tr: "Bir gün hangi evcil hayvanı alalım, adı ne olsun?" },
  { en: "What's a compliment from me you still think about?", tr: "Sana söylediğim ve hâlâ aklında olan bir iltifat?" },
  { en: "Sunrise or sunset together — which is more us?", tr: "Birlikte gün doğumu mu gün batımı mı — hangisi daha çok biziz?" },
  { en: "What's the first thing you'd do if we won the lottery?", tr: "Piyango kazansak ilk ne yapardın?" },
  { en: "What do you want more of from me this week?", tr: "Bu hafta benden daha çok ne istersin?" },
  { en: "What's a place we've never been that feels like it's waiting for us?", tr: "Hiç gitmediğimiz ama bizi bekliyormuş gibi hissettiren bir yer?" },
  { en: "What's your favorite 'us' smell — coffee, rain, something else?", tr: "En sevdiğin 'biz' kokusu ne — kahve, yağmur, başka bir şey?" },
  { en: "Which of our inside jokes still makes you laugh?", tr: "Aramızdaki hangi espri seni hâlâ güldürüyor?" },
  { en: "What's something brave you did because of me?", tr: "Benim sayemde yaptığın cesur bir şey?" },
  { en: "How do you want to be comforted on a bad day?", tr: "Kötü bir gününde nasıl teselli edilmek istersin?" },
  { en: "What's the best advice we've ever given each other?", tr: "Birbirimize verdiğimiz en iyi tavsiye neydi?" },
  { en: "If our love had a color, what would it be?", tr: "Aşkımızın bir rengi olsa ne olurdu?" },
  { en: "What's a small adventure we could have this weekend?", tr: "Bu hafta sonu yapabileceğimiz küçük bir macera?" },
  { en: "What part of our story would surprise strangers the most?", tr: "Hikâyemizin hangi kısmı yabancıları en çok şaşırtırdı?" },
  { en: "What's your favorite thing to do with me that costs nothing?", tr: "Benimle yapmayı sevdiğin, hiç para gerektirmeyen şey ne?" },
  { en: "What question do you wish I'd ask you?", tr: "Sana sormamı istediğin soru ne?" },
  { en: "What's one thing about me you never want to change?", tr: "Bende asla değişmesin istediğin bir şey?" },
  { en: "Where do you imagine us growing old?", tr: "Nerede yaşlanacağımızı hayal ediyorsun?" },
  { en: "What's the kindest thing I've done for you?", tr: "Senin için yaptığım en iyi kalpli şey neydi?" },
  { en: "If we started a tiny business together, what would it be?", tr: "Birlikte küçük bir iş kursak ne olurdu?" },
  { en: "What's your favorite time of day to be with me?", tr: "Benimle olmayı en sevdiğin saat hangisi?" },
  { en: "What's a language of love you want us to speak more?", tr: "Hangi sevgi dilini daha çok konuşmamızı istersin?" },
  { en: "What made you smile about me today?", tr: "Bugün bende seni ne gülümsetti?" },
  { en: "What's a hard question you've wanted to ask me?", tr: "Bana sormak isteyip de soramadığın zor bir soru?" },
  { en: "What holiday do you want to spend just the two of us?", tr: "Hangi bayramı ya da tatili sadece ikimiz geçirelim?" },
  { en: "What are three words that describe us?", tr: "Bizi anlatan üç kelime ne olurdu?" },
  { en: "What's the most spontaneous thing we've done together?", tr: "Birlikte yaptığımız en plansız şey neydi?" },
  { en: "What do you look forward to most about our future?", tr: "Geleceğimizde en çok neyi dört gözle bekliyorsun?" },
];
