// One question a day; both answer blind, revealed together. Grown-up and
// direct — never cutesy. Mix of intimacy, honesty, ambition and the future.
// Append freely; past days keep their recorded question via question_idx.

export interface ZuyaQuestion {
  en: string;
  tr: string;
}

export const ZUYA_QUESTIONS: ZuyaQuestion[] = [
  { en: "What do you want more of from me that you haven't asked for?", tr: "Benden daha çok ne istiyorsun ama hiç istemedin?" },
  { en: "When do you feel most desired by me?", tr: "Kendini bana en çok ne zaman arzulanır hissediyorsun?" },
  { en: "What have you changed your mind about since we met?", tr: "Tanıştığımızdan beri fikrini değiştirdiğin bir şey ne?" },
  { en: "Where do you honestly want us to be in five years?", tr: "Beş yıl sonra gerçekten nerede olmamızı istiyorsun?" },
  { en: "What boundary do you wish I respected more?", tr: "Daha çok saygı göstermemi istediğin bir sınırın ne?" },
  { en: "What makes you feel safe with me?", tr: "Yanımda kendini neyle güvende hissediyorsun?" },
  { en: "What's a risk you want us to take together?", tr: "Birlikte almak istediğin bir risk ne?" },
  { en: "What turns an ordinary night with me into a good one?", tr: "Benimle sıradan bir geceyi neyin güzel bir geceye çevirir?" },
  { en: "What do you need when you're stressed that I sometimes miss?", tr: "Stresliyken sana ne lazım, bazen kaçırdığım?" },
  { en: "Where do you like me paying attention to you?", tr: "Sana nereye ilgi göstermemi seviyorsun?" },
  { en: "What ambition of yours could I support better?", tr: "Daha iyi destekleyebileceğim bir hedefin ne?" },
  { en: "What did you learn about love from your family — good or bad?", tr: "Ailenden aşk hakkında ne öğrendin — iyi ya da kötü?" },
  { en: "When did you last feel truly understood by me?", tr: "En son ne zaman kendini bana gerçekten anlaşılmış hissettin?" },
  { en: "What's something between us you'd want to explore more?", tr: "Aramızda daha çok keşfetmek istediğin bir şey ne?" },
  { en: "What's a fear about us you don't say out loud?", tr: "Bizimle ilgili sesli söylemediğin bir korkun ne?" },
  { en: "What does a real apology from me look like?", tr: "Benden gerçek bir özür nasıl olur?" },
  { en: "What makes you trust someone — and do I do it?", tr: "Birine neyle güvenirsin — ve ben yapıyor muyum?" },
  { en: "When do you feel most like yourself around me?", tr: "Yanımda en çok ne zaman kendin gibisin?" },
  { en: "What do you want our home to feel like?", tr: "Evimizin nasıl hissettirmesini istiyorsun?" },
  { en: "What's a hard truth you think we avoid?", tr: "Kaçındığımızı düşündüğün zor bir gerçek ne?" },
  { en: "How do you want to be held when you're low?", tr: "Kötüyken nasıl sarılmak istersin?" },
  { en: "What's a promise you're a little afraid to make?", tr: "Vermekten biraz korktuğun bir söz ne?" },
  { en: "What's the most attractive thing about me that isn't physical?", tr: "Bende fiziksel olmayan en çekici şey ne?" },
  { en: "What do you need to hear from me more often?", tr: "Benden daha sık duyman gereken şey ne?" },
  { en: "Is there a resentment you're still holding onto?", tr: "Hâlâ tuttuğun bir kırgınlık var mı?" },
  { en: "What would make you feel chosen, again and again?", tr: "Seni tekrar tekrar seçilmiş hissettirecek şey ne?" },
  { en: "What are you curious to try but nervous to bring up?", tr: "Denemeyi merak ettiğin ama açmaya çekindiğin şey ne?" },
  { en: "In your ideal life, what is money supposed to buy us?", tr: "İdeal hayatında para bize ne almalı?" },
  { en: "What do you want me to stop doing?", tr: "Yapmayı bırakmamı istediğin şey ne?" },
  { en: "What's a memory I'm not part of that shaped who you are?", tr: "İçinde olmadığım, seni sen yapan bir anın ne?" },
  { en: "How should we handle it when we want different things?", tr: "Farklı şeyler istediğimizde bunu nasıl çözmeliyiz?" },
  { en: "What's the difference, for you, between being loved and being wanted?", tr: "Senin için sevilmekle istenmek arasındaki fark ne?" },
  { en: "What part of yourself are you still hiding a little?", tr: "Hâlâ biraz sakladığın bir yanın ne?" },
  { en: "What would you do this year if you weren't afraid?", tr: "Korkmasan bu yıl ne yapardın?" },
  { en: "What's your honest take on marriage — for us?", tr: "Evlilik hakkında dürüst fikrin ne — bizim için?" },
  { en: "When do you feel neglected by me?", tr: "Kendini benim tarafımdan ne zaman ihmal edilmiş hissediyorsun?" },
  { en: "Right now, do you need more closeness or more space?", tr: "Şu an neye ihtiyacın var: daha çok yakınlık mı, daha çok alan mı?" },
  { en: "What's a compliment you wish I'd give you?", tr: "Sana vermemi istediğin bir iltifat ne?" },
  { en: "What does desire feel like for you lately?", tr: "Son zamanlarda arzu sana nasıl hissettiriyor?" },
  { en: "Is there a decision we made that you'd revisit?", tr: "Verdiğimiz, yeniden ele almak istediğin bir karar var mı?" },
  { en: "What do you want to be true about us that isn't yet?", tr: "Bizimle ilgili henüz doğru olmayan neyin doğru olmasını istersin?" },
  { en: "What weakness of mine have you made peace with?", tr: "Barıştığın bir zayıflığım ne?" },
  { en: "When do you feel most respected by me?", tr: "Kendini benim tarafımdan en çok ne zaman saygı görmüş hissediyorsun?" },
  { en: "What's the bravest thing you've done for love?", tr: "Aşk için yaptığın en cesur şey ne?" },
  { en: "What do you want our arguments to sound like?", tr: "Tartışmalarımızın nasıl olmasını istersin?" },
  { en: "Which part of your future are you scared to plan?", tr: "Geleceğinin hangi kısmını planlamaktan korkuyorsun?" },
  { en: "What do I do that instantly relaxes you?", tr: "Yaptığım hangi şey seni anında rahatlatıyor?" },
  { en: "What unspoken rule between us would you change?", tr: "Aramızdaki, değiştireceğin sessiz bir kural ne?" },
  { en: "When do you feel like a real team with me?", tr: "Benimle ne zaman gerçek bir takım gibi hissediyorsun?" },
  { en: "What do you need to forgive yourself for?", tr: "Kendini ne için affetmen gerekiyor?" },
  { en: "What's something you want us to save toward?", tr: "Birlikte biriktirmek istediğin bir şey ne?" },
  { en: "Did you ever almost walk away — and what kept you?", tr: "Hiç neredeyse gittin mi — ve seni ne tuttu?" },
  { en: "What does feeling wanted in bed mean to you?", tr: "Yatakta istenmek senin için ne demek?" },
  { en: "What dream would you chase if I promised to catch you?", tr: "Seni tutacağıma söz versem hangi hayalin peşinden koşardın?" },
  { en: "What do you wish we did less of?", tr: "Neyi daha az yapmamızı isterdin?" },
  { en: "What's the truest thing you know about us?", tr: "Bizimle ilgili bildiğin en gerçek şey ne?" },
  { en: "What makes you feel powerful?", tr: "Seni ne güçlü hissettiriyor?" },
  { en: "What do you envy in other couples, if anything?", tr: "Başka çiftlerde kıskandığın bir şey var mı?" },
  { en: "What's a side of me you wish came out more often?", tr: "Bende daha sık ortaya çıkmasını istediğin bir yanım ne?" },
  { en: "How do you want to be comforted versus fixed?", tr: "Ne zaman teselli, ne zaman çözüm istiyorsun?" },
  { en: "What's something you've never told anyone but might tell me?", tr: "Kimseye anlatmadığın ama bana anlatabileceğin bir şey ne?" },
  { en: "What does a good life together actually look like to you?", tr: "Sana göre birlikte iyi bir hayat aslında nasıl görünüyor?" },
  { en: "What do you want to be forgiven for?", tr: "Ne için affedilmek istiyorsun?" },
  { en: "When do you feel furthest from me?", tr: "Benden en uzak ne zaman hissediyorsun?" },
  { en: "What would you never compromise on?", tr: "Asla taviz vermeyeceğin şey ne?" },
];
